PImage S1;
PImage Ft;
PImage Cesped;
PImage Inicio;
PImage Manito;
PImage opcion;
PImage Tierra;
PImage acerca;
PImage Sal_der;
PImage Sal_izq;
PImage EnLigDer;
PImage EnLigIzq;
PImage EnNorDer;
PImage EnNorIzq;
PImage EnPesDer;
PImage EnPesIzq;
void imagenes(){
  fondo = loadImage("assets/Cielo.png");
  Ft = loadImage("assets/Fondo-tierra.png");
  CamDere = loadImage("assets/Personaje/Prota.png");
  CamIzqu = loadImage("assets/Personaje/Prota(-1).png");
  Sal_der = loadImage("assets/Personaje/Prota-salto.png");
  Sal_izq = loadImage("assets/Personaje/Prota-salto(-1).png");
  Hui = loadImage("assets/Hub.png");
  Pi = loadImage("assets/Muestra.png");
  S1 = loadImage("assets/Escenario-1-Prueba.png");
  Cesped = loadImage("assets/Cespe.png");
  Tierra = loadImage("assets/Tierra.png");
  Inicio = loadImage("assets/Pantallas/Pantalla_titulo.png");
  Manito = loadImage("assets/Manito.png");
  opcion = loadImage("assets/Pantallas/Pantalla_opciones.png");
  acerca = loadImage("about/about.png");
  EnLigDer = loadImage("assets/Personaje/EnemigoL.png");
  EnLigIzq = loadImage("assets/Personaje/EnemigoL(-1).png");
  EnNorDer = loadImage("assets/Personaje/EnemigoN.png");
  EnNorIzq = loadImage("assets/Personaje/EnemigoN(-1).png");
  EnPesDer = loadImage("assets/Personaje/EnemigoP.png");
  EnPesIzq = loadImage("assets/Personaje/EnemigoP(-1).png");
}
